; Notes:
; priority=1 --> Lower priorities indicate programs that start first and shut down last
; killasgroup=true --> send kill signal to child processes too

; graceful timeout should always be lower than stopwaitsecs to avoid orphan gunicorn workers.
[program:frappe-bench-frappe-web]
command=/home/vishal/frappe-bench/env/bin/gunicorn -b 127.0.0.1:8000 -w 25 --max-requests 5000 --max-requests-jitter 500 -t 120 --graceful-timeout 30 frappe.app:application --preload
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/vishal/frappe-bench/logs/web.log
stderr_logfile=/home/vishal/frappe-bench/logs/web.error.log
stopwaitsecs=40
killasgroup=true
user=vishal
directory=/home/vishal/frappe-bench/sites
startretries=10

[program:frappe-bench-frappe-schedule]
command=/usr/local/bin/bench schedule
priority=3
autostart=true
stdout_logfile=/home/vishal/frappe-bench/logs/schedule.log
stderr_logfile=/home/vishal/frappe-bench/logs/schedule.error.log
user=vishal
directory=/home/vishal/frappe-bench
startretries=10



[program:frappe-bench-frappe-short-worker]
command=/usr/local/bin/bench worker --queue short,default
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/vishal/frappe-bench/logs/worker.log
stderr_logfile=/home/vishal/frappe-bench/logs/worker.error.log
user=vishal
stopwaitsecs=360
directory=/home/vishal/frappe-bench
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:frappe-bench-frappe-long-worker]
command=/usr/local/bin/bench worker --queue long,default,short
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/vishal/frappe-bench/logs/worker.log
stderr_logfile=/home/vishal/frappe-bench/logs/worker.error.log
user=vishal
stopwaitsecs=1560
directory=/home/vishal/frappe-bench
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10


[program:frappe-bench-frappe-pdf_queue-worker]
command=/usr/local/bin/bench worker --queue pdf_queue
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/vishal/frappe-bench/logs/worker.log
stderr_logfile=/home/vishal/frappe-bench/logs/worker.error.log
user=vishal
stopwaitsecs=5000
directory=/home/vishal/frappe-bench
killasgroup=true
numprocs=4
process_name=%(program_name)s-%(process_num)d
startretries=10




[program:frappe-bench-redis-cache]
command=/usr/bin/redis-server /home/vishal/frappe-bench/config/redis_cache.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/vishal/frappe-bench/logs/redis-cache.log
stderr_logfile=/home/vishal/frappe-bench/logs/redis-cache.error.log
user=vishal
directory=/home/vishal/frappe-bench/sites
startretries=10

[program:frappe-bench-redis-queue]
command=/usr/bin/redis-server /home/vishal/frappe-bench/config/redis_queue.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/vishal/frappe-bench/logs/redis-queue.log
stderr_logfile=/home/vishal/frappe-bench/logs/redis-queue.error.log
user=vishal
directory=/home/vishal/frappe-bench/sites
startretries=10




[group:frappe-bench-web]
programs=frappe-bench-frappe-web




[group:frappe-bench-workers]
programs=frappe-bench-frappe-schedule,frappe-bench-frappe-short-worker,frappe-bench-frappe-long-worker,frappe-bench-frappe-pdf_queue-worker




[group:frappe-bench-redis]
programs=frappe-bench-redis-cache,frappe-bench-redis-queue
